### ISSUE TITLE
.md files rename to upper case 

### ISSUE THREAD

**Issue by SATYAM1548** [ikrishg/reseter.css#143]
Project does't have a convention of .md files.
In order to make it more readable can I work on this

**Comment by GaryHilares** [comment]
Hey @SATYAM1548! Could you specify which convention is not being followed? The `.md` files seem pretty good to me.

**Comment by gptkrsh** [comment]
@SATYAM1548 This issue does not look like it exists, since there is no convention of .md files a whole. Apart, we do not have any non-external (no sourced from outside, CODE_OF_CONDUCT is sourced from Contributor Covenant, Licence is sourced from MIT etc) apart from README and CONTRIBUTING, it does not make sense to have a convention anyways
